define(function() {
    return {
        "properties": [{
            "name": "profileImageIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "menuTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingTextIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerImageSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerImageWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerImageHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "placeholderVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingTextIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuDirection",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerStyle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuAnimation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerAnimation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "menuOptions",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subMenuOptions",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableMenuItemAnimation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "animationSpeed",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "flxTargetContainer",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["removeAllMenuItem", "addMenuItems", "showSlidingMenu", "hideSlidingMenu"],
        "events": ["onFooterClick", "onProfileClick", "onShowSlidingMenu", "onHideSlidingMenu", "onMenuItemClick"]
    }
});